### PR TITLE
Add ArviZ to to env and 02-Instructor

### PR DESCRIPTION
**Pull request by canyon289**
@ericmjl Let me know if editing the notebooks to include ArviZ is still welcome. If so let me know if you'd like me to do a PR per notebook, or all in one shot.

And if its not no worries :)

### CODE REVIEW

**Comment by ericmjl** [comment]
@canyon289 this is still welcome! I think one PR per notebook might be easier to manage, what do you think?

**Comment by ericmjl** [comment]
Also, do ping me when you think this is ready! I have enabled the WIP bot, I'll first mark this as WIP in the title; when done, you can just remove it.

**Comment by ericmjl** [comment]
By the way, @hugobowne, please meet @canyon289! :smile:

**Comment by canyon289** [comment]
@ericmjl one at a time is fine. It makes is easier to review and iterate

@hugobowne Nice to meet you as well!

**Comment by ericmjl** [comment]
@hugobowne I looked over the rest of the PR series by @canyon289, and I think we're good to merge - review unnecessary! I'll also be setting up some automation to get the notebooks published nicely as a GitHub pages website.

**Pull request merged**
