### PR TITLE
Use binder directory for configuration files

### PR DESCRIPTION
**Pull request by matthewfeickert**
In response to @ericmjl's [tweet RE: Binder configuration file conflicts](https://twitter.com/ericmjl/status/1228092153462710273), this PR adopts the use of a `binder` directory for configuration files which eliminates any conflict as

>  [If a `binder/` folder is used, Binder will only read configuration files from that location (i.e. myproject/binder/requirements.txt) and will ignore those in the repository’s root](https://mybinder.readthedocs.io/en/latest/faq.html#can-i-put-my-configuration-files-outside-the-root-of-my-repository)

As placing the [Conda `environment.yml` config file](https://mybinder.readthedocs.io/en/latest/config_files.html#environment-yml-install-a-python-environment) affects the path that both the user focused documentation and the CI use, paths and docs that explicitly use the path to the config file are updated.

As this does now require users to think more explicitly about the path to the `environment.yml` at environment creation time I can understand that this might be something that could be a deal breaker for this PR. However, I think that most people should be fine with typing a few more letters and probably don't deeply care _where_ their environment config files live.

This also reverts the movement of the `Dockerfile` and the `.dockerignore` as this was just done to avoid the issue, but there is no reason to do this anymore so don't.

Finally, the Binder badge used is updated to reflect the modern (as of 2019) Binder badge (with logo).

### CODE REVIEW

**Comment by matthewfeickert** [comment]
For reference, the Binder build for this branch on my fork is here: https://mybinder.org/v2/gh/matthewfeickert/bayesian-stats-modelling-tutorial/use-binder-dir-example

**Comment by ericmjl** [comment]
Wonderful stuff, @matthewfeickert!

**Comment by ericmjl** [comment]
I appreciate all the thought you put into the PR, @matthewfeickert. This is how open source is supposed to be done! :smile:

**Comment by matthewfeickert** [comment]
Ah, thank you @ericmjl! That's so kind of you to say. :slightly_smiling_face: 

The work that you do for the Python community (like this true gem of a tutorial repo) is truly inspirational and I'm more then pleased if I can have helped out in a very small way.

**Comment by hugobowne** [comment]
Echoing sentiments in both directions here :)

**Pull request merged**
