### PR TITLE
Make far better for workshop (WIP; don't merge)

### PR DESCRIPTION
**Pull request by hugobowne**
@ericmjl Working on it! Please do not review until I request it.

### CODE REVIEW

**Comment by hugobowne** [comment]
@ericmjl notebook 1 is ready for feedback. I may make minor tweaks today or tomorrow.

I am discussing with @justinbois tomorrow and will likely make some changes after that. I'm interested to see how correlated your feedback will be with JB's.

**Comment by ericmjl** [comment]
# Programming Conventions

Let's standardize a bit on programming conventions. Usually I don't have strong opinions on this, but drawing on my prior experience in Science One at UBC, where algebraic conventions were harmonized between the physics and chemistry instructors, I think it's important to standardize (at least within one class) -- it's more for the learner, and less for the instructors.

One thing that I think is a pandas-centric convention is to use the selector syntax for column names, rather than attribute syntax (even though both are available). The reason for this is that the selector syntax is more general (particularly when non alphanumeric characters are present in the column names), and I think there are more examples of the use of selector syntax than attribute syntax.

**Comment by ericmjl** [comment]
# Consistent Data Prep

Another thing that I did in the notebooks that I'm creating is to use highlight some of pyjanitor's data cleaning functions, such as (ahem) cleaning column names! For example, in loading the finches dataset, I have added the following:

```python
df = (jn.DataFrame(df)  # wrap dataframe in a Janitor dataframe.
      .clean_names()    # clean column names
      .rename_column('blenth', 'beak_length')  # rename blength to beak_length (readability fix)
      .rename_column('bdepth', 'beak_depth')   # rename bdepth to beak_depth (readability fix)
      .label_encode('species')  # create a `species_enc` column that has the species encoded numerically
     )
```

Since the finches dataset permeates the whole tutorial, it may help with continuity if this little detail is taken care of.

**Comment by hugobowne** [comment]
@ericmjl thanks for all of this.

Happy to change to selector syntax, although I may ask that we merge this PR before I do. Will that be ok?

Adding in such data prep so early will distract from the pedagogy, which is difficult enough, particularly as I intend to have as little boilerplate code as possible. A solution for this would be to clean the file before the tutorial. Thoughts?

And were those the only two things?

**Comment by hugobowne** [comment]
@ericmjl also: NB2 is ready for feedback.

I'll also change to selector syntax here. I also need to do a PEP 8 pass, add in some comments

AND add in some text/eqn based descriptions for sections 3&4 (I'll get to this tomorrow).

**Comment by ericmjl** [comment]
> Adding in such data prep so early will distract from the pedagogy, which is difficult enough, particularly as I intend to have as little boilerplate code as possible. A solution for this would be to clean the file before the tutorial. Thoughts?

Let's riff off that - I now remember that in Network Analysis Made Simple, I provided custom functions for the class to load data of interest (in our case, it would be `load_finches()`, `load_baseball()`, `load_sterilization()`, etc.). I will get that done for each dataset that is relevant to both our notebooks; let's handle the final clean up over pair coding on Monday night then.

**Comment by ericmjl** [comment]
> And were those the only two things?

Yep, just those. I've looked at the content of the notebooks, but can't find anything to critique at the moment - mostly I'm looking forward to seeing how you teach your material!

**Comment by ericmjl** [comment]
Now reviewing NB2!

**Comment by ericmjl** [comment]
Just some questions: Is a bit more verbiage required here? For me, when I hit that section, I wasn't quite sure what would happen - would this be you guiding the class? And would we need a bit more motivation provided as text, or is it appropriate to leave it as is?

screenshot 2018-07-07 09 01 47

**Comment by ericmjl** [comment]
Trivial detail here, but I think sampling for 2000 steps might give a distribution that is slightly smoother.
screenshot 2018-07-07 09 15 30

**Comment by hugobowne** [comment]
wrt

> Just some questions: Is a bit more verbiage required here? For me, when I hit that section, I wasn't quite sure what would happen - would this be you guiding the class? And would we need a bit more motivation provided as text, or is it appropriate to leave it as is?

Definitely going to include more text here. My to-do was

> AND add in some text/eqn based descriptions for sections 3&4 (I'll get to this tomorrow).


Plan is to add a description of how to build a model: figure out the parameters, assign priors and likelihoods, than sample using MCMC to get posterior.

I'll mention in the hands on what the priors and likelihood are etc...

Yes will sample 2,000 steps.

**Comment by ericmjl** [comment]
> Definitely going to include more text here. My to-do was
> > AND add in some text/eqn based descriptions for sections 3&4 (I'll get to this tomorrow). 
> 
> Plan is to add a description of how to build a model: figure out the parameters, assign priors and likelihoods, than sample using MCMC to get posterior.

My apologies! Didn't make that connection earlier on.

**Comment by hugobowne** [comment]
@ericmjl i've added more verbiage to section 3. check it out !  I'm pretty happy with it.

**Comment by ericmjl** [comment]
> @ericmjl i've added more verbiage to section 3. check it out ! I'm pretty happy with it.

As am I! Can't wait to see how you teach it! :smile:

**Comment by ericmjl** [comment]
I'm good to go with what you've got! I will merge.

**Pull request merged**
