### PR TITLE
Make NBs 1&2 modular (WIP; do NOT merge)

### PR DESCRIPTION
**Pull request by hugobowne**

### CODE REVIEW

**Comment by hugobowne** [comment]
a la this here: https://github.com/ericmjl/bayesian-stats-modelling-tutorial/issues/72#issuecomment-489215928

I've modularized NB1. About to do same for NB2.

- [ ] I'll first do the instructor NBs. 
- [ ] Then, when @ericmjl &  I are aligned on them, I'll do the student NBs.

Currently naming new NBs 1-a,  1-b, 2-a, 2-b. Any thoughts on naming conventions, @ericmjl ?

**Comment by hugobowne** [comment]
@ericmjl instructor NBs 1a/1b/2a/2b ready for review.  See above comments for more context

**Comment by ericmjl** [comment]
@hugobowne thanks a ton for doing this! Seeing what you've covered until NB 2b means I actually can get into thinking about the entire data-generating process earlier than I originally anticipated. This is great.

The comments I have are mostly stylistic. The biggest one concerns headers:

image

Would you be ok if I re-did the headers so that they reflect the logical hierarchy of each notebook more accurately? The hardest part for me navigating the notebooks were:

1. Hands-on vs. HANDS ON
1. Thematic headers that were sub-headers of others. For example, I see ECDFs as parental to the ECDF hands-on.

**Comment by hugobowne** [comment]
@ericmjl yes the more I think about it, the more enriching I think for everybody that we introduce thinking about the entire data-generating process as early as possible (and also  ECDFs). I like to think of data-generating processes as first-class citizens of these lessons :) 

I'm fine with you making _any stylistic edits_.  When you write:

> The comments I have are mostly stylistic.

are there any other comments?

**Comment by ericmjl** [comment]
Thinking about it again, I don’t have any other stylistic edits for now. 

Ok, I will go into your branch and push up a few changes. Will loop back shortly.

**Comment by ericmjl** [comment]
@hugobowne I've finished my stylistic changes. 

I hope you don't mind; doing these little tasks was great for me to go over the material with a fine-toothed comb.

Having reviewed the material, these look like the teaching points, in my own words.

1. Probability is a measure of credibility over a space of values. It's like assigning money to the number line.
1. Joint probability asks us to assign credibility points to the occurrence of two values. Conditional probability, on the other hand, asks us to figure out how many credibility points to assign to the number line for a given random variable, given knowledge of another one.
1. Joint and conditional probability bring us to Bayes theorem. We model the parameter space and data space as being jointly distributed, and infer what we should believe about parameters given the data.
1. Parameters can be described by probability distributions. They are stories of processes by which the data are generated. We can use this as part of the language for describing more complex models of data generation.

Beyond this foundation, everything else is nothing more than "describe data generating processes using probability distributions, and condition them on known data."

**Comment by hugobowne** [comment]
Yep agreed wrt teaching points @ericmjl. 

A key point is the ability to match data to the stories that generate the data: 

- In this sense, the **story** is isomorphic to the data generating process. Then we can use simulation of the story to generate the data of the story. This allows us to compare our real-world data to our story (or model). One way to do this is using the ECDF.

This is the key takeaway for me ^

**Comment by ericmjl** [comment]
@hugobowne just wanted to make sure this ball isn’t dropped - will you be making the student notebooks? If you need the personal time, do let me know, I can work on it. In fact, if I work on making it, the fine-toothed combing will help me go through the material again, so I’ll hopefully be more effective with the material you’ve created. 

Lmk what you think; if I don’t hear back by, say, evening ET July 4, I will go ahead and do the changes.

**Comment by hugobowne** [comment]
@ericmjl Yep I was planning to do this over the weekend. I reckon it can mostly be done from the previous iteration of NBs pre-split, e.g. https://github.com/ericmjl/bayesian-stats-modelling-tutorial/blob/master/notebooks/01-Student-Probability_a_simulated_introduction.ipynb

If you would like to do it from these, as you'll be teaching the tutorial & there may be personal decisions involved wrt tutorial cadence & style, I'm also okay with that.

Let me know (I'm on Sydney time FYI: ET+14).

**Comment by ericmjl** [comment]
Okie dokes, I'll take care of it - so that I can get familiar with the material.

Have a good rest, Hugo - I hope I'll do the material justice :smile:, especially with all the thought you've put into it.

**Comment by hugobowne** [comment]
If there's anybody I'd trust to do the material justice, it's you @ericmjl. 

And I'm looking forward to hearing about your experience teaching it & how it resonates with you.

I want to think more about teaching/thinking statistics via the story telling of data generating processes & your experience here will be invaluable.

**Pull request merged**
